
development:
  adapter: postgresql
  database: exampleapp_development
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

test: &test
  adapter: postgresql
  database: exampleapp_test
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

production:
  adapter: postgresql
  database: exampleapp_production
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0
